### ISSUE TITLE
Uncaught TypeError: _react.default.createRef is not a function

### ISSUE THREAD

**Issue by PainKKKiller** [tbleckert/react-select-search#25]
Nice component, but when I tried to use it in my project (react 16.2 version) I've got error

`Uncaught TypeError: _react.default.createRef is not a function
    at new SelectSearch (index.js?cd67:180)
    at new SelectSearch (eval at <anonymous> (utils.js?0184:112), <anonymous>:5:7)
    at constructClassInstance (react-dom.development.js?cada:6355)
    at updateClassComponent (react-dom.development.js?cada:7839)
    at beginWork (react-dom.development.js?cada:8225)
    at performUnitOfWork (react-dom.development.js?cada:10224)
    at workLoop (react-dom.development.js?cada:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:581)
    at invokeGuardedCallback (react-dom.development.js?cada:438)`

**Comment by PainKKKiller** [comment]
Am I right that it can't work with react versions lower than 16.3? Should it be pointed out in documentation?

**Comment by PainKKKiller** [comment]
Anyway,  updated project to 16.3 and now when I click on component I getting another error:

`index.js?cd67:352 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at ProxyComponent.handleFocus (index.js?cd67:352)
    at ProxyComponent.componentDidUpdate (index.js?cd67:224)
    at commitLifeCycles (react-dom.development.js?cada:8778)
    at commitAllLifeCycles (react-dom.development.js?cada:9946)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:581)
    at invokeGuardedCallback (react-dom.development.js?cada:438)
    at commitRoot (react-dom.development.js?cada:10050)
    at performWorkOnRoot (react-dom.development.js?cada:11017)
    at performWork (react-dom.development.js?cada:10967)
handleFocus @ index.js?cd67:352
componentDidUpdate @ index.js?cd67:224
commitLifeCycles @ react-dom.development.js?cada:8778
commitAllLifeCycles @ react-dom.development.js?cada:9946
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
commitRoot @ react-dom.development.js?cada:10050
performWorkOnRoot @ react-dom.development.js?cada:11017
performWork @ react-dom.development.js?cada:10967
batchedUpdates @ react-dom.development.js?cada:11086
batchedUpdates @ react-dom.development.js?cada:2330
dispatchEvent @ react-dom.development.js?cada:3421
react-dom.development.js?cada:9747 The above error occurred in the <SelectSearch> component:
    in SelectSearch (created by OnClickOutside(SelectSearch))
    in OnClickOutside(SelectSearch) (created by Settings)`

**Comment by tbleckert** [comment]
Yes, you're correct, it doesn't support React versions that doesn't have the `createRef`. I'll close this issue for now, if you can describe the bug in more detail we can open it up and take a look at it.

**Comment by waqaramjad** [comment]
facing same issue
